# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PluralithHomebrewTap < Formula
  desc "Testing"
  homepage "https://pluralith.com"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-homebrew-tap/releases/download/v0.1.4/pluralith_cli_tap_darwin_amd64_v0.1.4.tar.gz"
      sha256 "fc174f5be7257909d4187d1ed080788197a7f6c5693ca331bf34a9eb93b84fc0"

      def install
        bin.install "pluralith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-homebrew-tap/releases/download/v0.1.4/pluralith_cli_tap_linux_amd64_v0.1.4.tar.gz"
      sha256 "2bbf10f6cfc2e29b0b8d33c64ba94b453528a3b21ec2e5f3876ffbc31f0a7def"

      def install
        bin.install "pluralith"
      end
    end
  end

  test do
    system "#{bin}/pluralith version"
  end
end
