# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pluralith < Formula
  desc "Pluralith is a tool for Terraform state visualisation and automated infrastructure documentation"
  homepage "https://pluralith.com"
  version "0.1.19"

  on_macos do
    url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.19/pluralith_cli_tap_darwin_amd64_v0.1.19.tar.gz"
    sha256 "04c13f95f7cfe8edac6bd4bb50014671ffa73f8a5c4fe1b9d7a5fefdea3a39d0"

    def install
      bin.install "pluralith"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pluralith
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.19/pluralith_cli_tap_linux_amd64_v0.1.19.tar.gz"
      sha256 "11921fcdf1b2e03fd86b1365457b9c7838ee7681a749fb01bbe9e4fda21826e7"

      def install
        bin.install "pluralith"
      end
    end
  end

  test do
    system "#{bin}/pluralith version"
  end
end
