# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PluralithHomebrewTap < Formula
  desc "Testing"
  homepage "https://pluralith.com"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-homebrew-tap/releases/download/v0.1.4/pluralith_cli_darwin_amd64_v0.1.4.tar.gz"
      sha256 "7af25f432e829e487338bd952c8fd7cd83d9246efd351491b8dea44efd5273af"

      def install
        bin.install "pluralith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-homebrew-tap/releases/download/v0.1.4/pluralith_cli_linux_amd64_v0.1.4.tar.gz"
      sha256 "e93ca52727fdcb10da38f9cab445e4e1135364bd3c8b957c97af6e21c497a8a1"

      def install
        bin.install "pluralith"
      end
    end
  end

  test do
    system "#{bin}/pluralith version"
  end
end
