# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pluralith < Formula
  desc "Pluralith is a tool for Terraform state visualisation and automated infrastructure documentation"
  homepage "https://pluralith.com"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.5/pluralith_cli_tap_darwin_amd64_v0.1.5.tar.gz"
      sha256 "a4ec776317f1fa8e347e78f118ef3d3a2410431e44b5f1e3cd29330d7428513c"

      def install
        bin.install "pluralith"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.5/pluralith_cli_tap_linux_amd64_v0.1.5.tar.gz"
      sha256 "7f31913e9c69fc2395363701e592897023b5f9d57ef12e30e4b1aa6b28c618d9"

      def install
        bin.install "pluralith"
      end
    end
  end

  test do
    system "#{bin}/pluralith version"
  end
end
