# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pluralith < Formula
  desc "Pluralith is a tool for Terraform state visualisation and automated infrastructure documentation"
  homepage "https://pluralith.com"
  version "0.1.10"

  on_macos do
    url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.10/pluralith_cli_tap_darwin_amd64_v0.1.10.tar.gz"
    sha256 "df89ae14681f375969127d694f79a0c113a13e3af1a1e56837eb73b59d68891f"

    def install
      bin.install "pluralith"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Pluralith
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Pluralith/pluralith-cli/releases/download/v0.1.10/pluralith_cli_tap_linux_amd64_v0.1.10.tar.gz"
      sha256 "bd864e45f641a6f8d0eef5c4000a670c8ec3597beae14fd21eaeb4a69aff4a34"

      def install
        bin.install "pluralith"
      end
    end
  end

  test do
    system "#{bin}/pluralith version"
  end
end
